theme: lanyonesque
markdown_extensions: ['extra', 'sane_lists', 'codehilite']
site:
    title: Lanyonesque
    base_url: https://wmk-example.net
    leading_path: ''
    tagline: A port of the Jekyll theme Lanyon to wmk
    lang: en
    date_format: "%d %b %Y"
    datetime_format: "%d %b %Y %H:%M"
    description: |
        This is an example site illustrating Lanyonesque,
        which is a port of the Jekyll theme Lanyon to wmk.
    paginate: 4
    posts_list_detail: full
    author: Dr. Hastie Lanyon
    author_email: hl@wmk-example.net
    body_css_class: layout-reverse sidebar-overlay
